# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='colaborators',
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='card',
            name='assigned',
        ),
        migrations.AlterField(
            model_name='card',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='boards.Board'),
        ),
    ]
