# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20171206_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due_date',
        ),
    ]
