# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_card_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='satatus',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Backlog'), (1, 'Freezer'), (2, 'To-Do'), (3, 'On going'), (4, 'Test'), (5, 'Done')], default=0),
        ),
    ]
